-- +goose Up
CREATE TABLE feeds (
	id UUID PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	name VARCHAR(120) NOT NULL,
	url VARCHAR(240) NOT NULL UNIQUE,
	user_id UUID NOT NULL,
	CONSTRAINT fk_users
	FOREIGN KEY (user_id)
	REFERENCES users(id) 
	ON DELETE CASCADE
);

-- +goose Down
DROP TABLE feeds;
