-- +goose Up
CREATE TABLE posts (
	id UUID PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title VARCHAR(250) NOT NULL,
	url VARCHAR(250) NOT NULL UNIQUE,
	description VARCHAR(5000) NOT NULL,
	published_at TIMESTAMP,
	feed_id UUID NOT NULL,
	CONSTRAINT fk_feed_id
	FOREIGN KEY (feed_id)
	REFERENCES feeds(id)
	ON DELETE CASCADE
);

-- +goose Down
DROP TABLE posts;
